### ISSUE TITLE
No accented letters suport

### ISSUE THREAD

**Issue by guicercal** [davidenke/angular-material-keyboard#7]
Hello, i'm from Brasil and i'm using Angular Material Keyboard in a project. I checked today that accented letter dont work! i tried to type a letter before and after the accents but with no results.. 

How could i use letters with accents??

**Comment by davidenke** [comment]
Hi,

the easiest way would be to provide a custom keyboard layout since modifying the input that way isn't imlemented. You can provide multiple chars for every key which will be accessible by using e.g. the alt key.

**Comment by guicercal** [comment]
Thanks for the reply! i'll implement that solution! :D
